apiVersion: v1
kind: ServiceAccount
metadata:
  name: signup-app-service-account
  namespace: default
  annotations:
    # This magic annotation tells EKS to give this pod AWS permissions
    eks.amazonaws.com/role-arn: "arn:aws:iam::352183399586:role/cloud-signup-prod-pod-role"